### ISSUE TITLE
Gallery Confusion

### ISSUE THREAD

**Issue by rodbrock** [kylegilman/video-embed-thumbnail-generator#213]
I'm at a loss on how to create a gallery and the documentation is thin on the subject. If I manually type  the shortcode like so, it works: 
[KGVID gallery="true" gallery_include="133,104,128" gallery_orderby="desc" gallery_thumb="450"]
Isn't there a way to click on the "add media" button and select multiple videos from the media manager and then insert? Am I overlooking something here?

What's even more confusing is that the "Post ID" field in the media manager (when inserting), under the "Gallery Settings (all optional)" section is neither the video's ID nor the Wordpress post that I am trying to insert it into.

**Comment by kylegilman** [comment]
It seems like you figured out how it works. If the documentation is thin I would appreciate some tips on what would help you. I can make guesses but I don't know what people need until they tell me. I understand that it would be nicer if you could select multiple videos and have them convert in to a single gallery shortcode, but so far I've been unable to determine a way to do that. If you've found another plugin that does that, I would be very interested to see it so I can get a look under the hood. 

The Post ID you see in the gallery settings field is the parent post of the current video. You can use that field to make a gallery of videos that are attached to that other post. The gallery shortcode is much simpler if you use WordPress's media management system to your advantage and attach the videos to the post you're embedding them in. Then you don't need any of the attributes like `gallery_include` which is getting more and more difficult to use because WordPress is making it harder to see the IDs of the videos with every release.

**Comment by rodbrock** [comment]
Thanks for the reply. What I needed was a Lightbox style popup for the HTML5 video, which you'd think there would be many options out there, but there really isn't. Yours is good. I also needed galleries to be easily created because the client will be doing it.

I ended up finding another Lightbox plugin that handles HTML5 video fairly good (not as nice as yours) and I use it in conjunction with your plugin. As for the gallery, each video is a separate post and I filter them out by category. The thumbnail creation feature of your plugin is really fantastic! Actually, it's a super useful plugin altogether.

Cheers!

**Comment by kylegilman** [comment]
Which popup gallery plugin are you using? I'm still trying to figure out the best way to simplify creation of complicated galleries.

**Comment by rodbrock** [comment]
I'm not using a gallery, only a Lightbox that supports html5 video. I figured out a gallery workaround by having every video as a single post in a specific category then only displaying that category on a page with its featured image as the thumbnail. 

Joel
