### ISSUE TITLE
Embed code doesn't show in others websites

### ISSUE THREAD

**Issue by danzish** [kylegilman/video-embed-thumbnail-generator#236]
I have a website with some subdomains. One of them it's a video gallery, where I installed this plugin and is working fine. When I post a video, it shows the embed code above of it, what it's great. But when I copy this embed code and paste it in another subdomain, the player works fine, but it doesn't show the embed code, what is a problem because no one can get the embed code to put it in another website, if they want to.

For example, the video gallery subdomain:
http://videos.potterish.com/2015/david-heyman-revela-que-um-rosto-familiar-voltou-para-o-mundo-magico-em-animais-fantasticos/

Embeding it in another subdomain, the embed code is lost:
http://potterish.com/2015/01/david-heyman-revela-que-um-rosto-familiar-voltou-para-o-mundo-magico-em-animais-fantasticos/

The embed code itself:
< iframe allowfullscreen src='http://videos.potterish.com/wp-content/uploads/2015/Janeiro/David_Heyman_revela_informacoes-_sobre_Animais_Fantasticos2.mp4' frameborder='0' scrolling='no' width='426' height='240' autoplay='false'></iframe>

I would like the embed code was always being shown, is it possible?

PS: also the autoplay='false' function in the second site it doesn't working and I don't know why...

**Comment by kylegilman** [comment]
This is an interesting problem. The plugin is generating the wrong embed code. It's linking directly to the video file instead of the video player. The code should look more like this

`<iframe allowfullscreen src='http://www.kylegilman.net/?attachment_id=2770&kgvid_video_embed[enable]=true' frameborder='0' scrolling='no' width='730' height='410'></iframe>` 

For some reason the plugin doesn't think your video is in the WordPress database. Is that true? What's the shortcode you're using for that video?

And autoplay is not a valid attribute for an iframe, so there's no way to make that work.

**Comment by danzish** [comment]
Hey!
When I create a new post, I go to "Insert new media", and then "embed video from URL". I choose this option because all my videos are really big, so I send them to my server and copy video file URL and put it in this option. After that, the shortcode generated is this:
[KGVID poster="http://videos.potterish.com/wp-content/uploads/2015/Janeiro/David_Heyman_revela_informacoes-_sobre_Animais_Fantasticos2.jpg" width="426" height="240"]http://videos.potterish.com/wp-content/uploads/2015/Janeiro/David_Heyman_revela_informacoes-_sobre_Animais_Fantasticos2.mp4[/KGVID] 
But even with the "overlay embed code" function checked in plugin's settings, it didn't show the embed code, as you can see in the printscreen I'm sending to you. For this reason, I needed to add manually the "embedcode" function in the html. The final shortcode is this:
[KGVID embedcode="http://videos.potterish.com/wp-content/uploads/2015/Janeiro/David_Heyman_revela_informacoes-_sobre_Animais_Fantasticos2.mp4" poster="http://videos.potterish.com/wp-content/uploads/2015/Janeiro/David_Heyman_revela_informacoes-_sobre_Animais_Fantasticos2.jpg" width="426" height="240"]http://videos.potterish.com/wp-content/uploads/2015/Janeiro/David_Heyman_revela_informacoes-_sobre_Animais_Fantasticos2.mp4[/KGVID]
Am I doing something wrong?


Date: Sun, 26 Jul 2015 09:05:25 -0700

**Comment by kylegilman** [comment]
The plugin uses information from the WordPress database to create the embedded player. Any video that isn't in the database can't have a valid embed code, which is why it won't show up even with the embed code option enabled. I recommend using the Add From Server plugin to get your large videos into the WordPress database. That should fix your problem.
