### ISSUE TITLE
I need to generate a post for each video I upload

### ISSUE THREAD

**Issue by Hazemwd** [kylegilman/video-embed-thumbnail-generator#245]
I need to know where to put my code which generates a wordpress post for each video.
So that each post's title is the original name of the uploaded video.

Please help me, and THANKS in advance.
@kylegilman

**Comment by kylegilman** [comment]
This will likely be a premium feature in a future version of the plugin. I'm not going to write the code for you, but if you just need a push in the right direction, use the `add_attachment` hook. The function will have the video's post_id, which you can use to check if the attachment is a video, then get the title of the video, and then create a new post using that information and `wp_insert_post`

**Comment by Hazemwd** [comment]
You're great :)
I'll try this and get back to you if there were any problems.

btw, would you please have a look on this question ?
http://wordpress.stackexchange.com/questions/203861/wordpress-default-video-player-not-loaded-in-a-custom-theme

It is about your plugin.

**Comment by kylegilman** [comment]
I know you're running on localhost, but there is no way for me to answer that question without seeing your website. Maybe your custom theme doesn't run `wp_head()` or `wp_footer()` or maybe there's a JavaScript error earlier on the page unrelated to the plugin that's halting JavaScript execution and breaking the video player. Or it's some other reason I can't guess without seeing the page.

**Comment by Hazemwd** [comment]
Thanks for your reply
Here is the contents for the single.php file

http://pastebin.com/fAfTTHv5

in both header and footer I'm including the jquery and bootstrap asssets.
As I think the video.js is automatically included once it is enabled by your plugin as the wordpress "twentyfifteen" theme does not have the video.js files included.

**Comment by kylegilman** [comment]
Knowing the contents of single.php doesn't get us anywhere. I need to see a live website in order to troubleshoot well. I can tell you that hardcoding jQuery and other JavaScripts or CSS is a recipe for trouble. Run `wp_head()` in the header and `wp_footer()` in the footer. Otherwise all kinds of things don't work, not just my plugin. As long as both of those run, jQuery and all the necessary JS/CSS assets will be output in the right place. Either the header or the footer, depending on what other plugins you're using.

https://codex.wordpress.org/Function_Reference/wp_head
https://codex.wordpress.org/Function_Reference/wp_footer

**Comment by Hazemwd** [comment]
I'm really grateful for you, I forgot to include these two functions in my code.
It is solved now.
