### ISSUE TITLE
micro data: description is missing

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#275]
Hi,

I tested a single article with video inserted at the structured data testing tool and video object has an error: description is missing. 

Can you please check, because it seems, that your plugin delivers the videoObject. You can test it with https://iliastest.intelec.uni-passau.de/wordpress/2015/12/test/

Thanks and regards,

**Comment by kylegilman** [comment]
If there's no text provided, what would you expect to be in the description tag? If you don't want any text in the post, you can manually provide a description in the description field in the WordPress media library.

**Comment by benhartwich** [comment]
It could autogenerate the description from post entry?

**Comment by kylegilman** [comment]
Yes, normally if you don't provide a description, the beginning of the post content is used for the description. A description tag is generated in your test post, but it's just " ". In that post, what text do you expect to see in the description? I can't tell precisely how your template works, but it looks like there might be some sort of modular structure to your posts. From the perspective of WordPress, is the text you're expecting to appear in the description in the content of the post that the shortcode is in? Do you have a manual excerpt that might be interfering with an auto generated description? Are you using custom meta tags for the text instead of the main post content window? Also, you appear to have a development version of the plugin running. I can't tell when you downloaded it, but it's always possible you have a version that has a buggy version of the description generator.

**Comment by benhartwich** [comment]
Hi,

I´ve uploaded the latest build on github till now. Now I´ve got the error: name is missing on video object. But the video name is also auto generated. It seems that you´ve something solved, but another issue is made.

**Comment by kylegilman** [comment]
I didn't solve anything, I just trimmed the empty space from the description so the plugin generated the default description, which is "Video" and isn't very useful to you. I suspect the old version of the plugin made a name that was just "false" which is worse than nothing. Because of the nature of your site, the plugin is not getting the metadata it usually expects, and I need more information, which is why I asked all those questions.

In the test post, what text do you expect to see in the description? I can't tell precisely how your template works, but it looks like there might be some sort of modular structure to your posts and I can't tell what the post_content is. From the perspective of WordPress, is the text you're expecting to appear in the description in the post_content that the shortcode is in or are you using some meta tags to generate the text? How is the video added to the post? Is it a template tag or is it a shortcode in the post_content?

**Comment by kylegilman** [comment]
Closing old support issues. If you're still experiencing a problem please open a new issue.
