### ISSUE TITLE
Black border at the top of video-js player

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#306]
Hi,

I´ve got a little black border at each video player, which is displayed. I´ve figured out, that it is the background color auf video-js. So it seems that the height is not accurate set. Can you please have a look and give me a hint how to solve it: 
http://univideo.uni-passau.de/2013/01/headmates-spring-2012-werbespot/

**Comment by kylegilman** [comment]
Always warn people when you post links to loud autoplaying videos. The height of the player is set to 507.25 instead of 506.25. Your theme has a bunch of styles that affect the sizing of videos and uses the old 56.25% padding trick which can lead to rounding issues. I don't know exactly what your theme is doing to get that number, but I'd recommend you just change the player's background color to white.

```
.video-js.kg-video-js-skin {
    background-color: white;
}
```

**Comment by benhartwich** [comment]
Thanks, yes that´s the best solution.
