### ISSUE TITLE
Facebook OG Data

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#315]
Hi,

I tried to use the og:data module of your plugin at facebook. Facebook recognizes the video and loads a video player, when a link is shared, which has a mp4 file embedded. But when I hit the play button, the video is not played: I see a blue string "Download video". Perhaps it´s because the og:video-sec is not generated? 
I tried the open graph debugger tool, there are a few warning, but no problems.

Example link: https://univideo.uni-passau.de/2016/03/collapsed-minds-neuroleptic-empire-official-music-video-2015/

I´ve tried this at a fresh wordpress install with the default twenty fifteen theme and no other plugins, but there is no player loaded, when a link is shared, although the tags are available.

**Comment by kylegilman** [comment]
You should be getting an og:video:secure_url tag and that's probably why you can't play the video in Facebook posts, but I don't understand why you're not getting one. You should have several other tags that aren't there including og:video:type, og:video:width and og:video:height. There's no way for the plugin to only write the og:video tag and not the others. Are you embedding the video using a do_shortcode() template tag rather than shortcode in the post content? I suspect there's another mechanism creating those tags. Does disabling the Open Graph option in my plugin's settings page have any effect on the tags that are generated?

**Comment by benhartwich** [comment]
I use `echo do_shortcode('[KGVID]'.$file.'[/KGVID]');` for inserting the video automatically within the header section. 
I´ve deactivated the option, but nothing changed. It seems, that the theme generates some codes, because other plugins can´t be the reason for. Can you force tag generation by your plugin or add the secure url, when it´s not available?

**Comment by kylegilman** [comment]
The problem I have to get around is that if the shortcode isn't in the post_content, by the time the template executes the shortcode via `do_shortcode()` somewhere in the template, it's too late to add anything to the header, because `wp_header()` is long gone. It's fine to load JavaScripts later because those can go in the footer, which speeds up load time anyway, but Open Graph tags can't be outside of `<head>`. I need a way to put the shortcode information into the database so it's available to the plugin while the header is being created. The solution I built yesterday involves saving a custom post_meta the first time the page is loaded. It's not my favorite choice, but I think it will work.

**Comment by benhartwich** [comment]
Unfortunately the problem isn´t solved. I´ve installed the latest version.

**Comment by kylegilman** [comment]
Yes. That's why this issue is still open.

**Comment by benhartwich** [comment]
I think, there are some tags missing perhaps. The following article names the different og tags: https://support.brightcove.com/en/video-cloud/docs/setting-videos-not-hosted-brightcove-play-within-facebook

```
<meta property="og:title" content="Add-Video-Title"/>
  <meta property="og:description" content="Add-Video-Description"/>
  <meta property="og:type" content="movie"/>
  <meta property="og:video:height" content="270"/>
  <meta property="og:video:width" content="480"/>
  <meta property="og:url"  content="Add-URL-Of-Page-Hosting-Player"/>
  <meta property="og:video" content="Add-Video-URL">
  <meta property="og:video:secure_url" content="Add-Secure-Video-URL">
  <meta property="og:image" content="Add-VideoStill-URL"/>
  <meta property="og:video:type" content="application/x-shockwave-flash">
```

I´ven´t found any information about that, but it seems that only specific video hoster can use the video playback function at facebook directly - have you got any knowledge about this?

**Comment by kylegilman** [comment]
It is true that only whitelisted domains like YouTube and Vimeo are allowed to embed and play back styled video players, but Facebook will play an unstyled video in the timeline if all the tags are right. Take a look at the tags in the source code of [this post on my development website](http://www.kylegilman.net/dev/2015/10/25/single-video/) and try posting the link on Facebook. It should play in your timeline. I'm not sure why you're not getting more Open Graph tags than you are. Are you running the most recent version from GitHub? Is your `do_shortcode` running outside the loop for some reason? Is your theme somehow overriding the tags generated by the plugin? Are your videos not in the WordPress database?

**Comment by benhartwich** [comment]
Yes, your example is working. The theme seems to generate a few lines, but these shouldn´t override anything, because you´re just adding video og tags, which aren´t defined before:
```
            <meta property="og:title" content="Lehrvideo &#8211; Tennis: Gerader Vorhandschlag"/>
            <meta property="og:type" content="website" />
            <meta property="og:image" content="https://univideo.uni-passau.de/wp-content/uploads/2016/04/tennis-gerader-vorhandschlag_thumb50.jpg"/>
            <meta property="og:url" content="https://univideo.uni-passau.de/2016/04/lehrvideo-tennis-gerader-vorhandschlag/"/>
            <meta property="og:site_name" content="Univideo"/>        
            <meta property="og:description" content=""/>
```
The videos are placed at the header.php with:
```
if ($file != NULL && !has_shortcode( $content, '[KGVID]') ) {

							echo do_shortcode('[KGVID autoplay="true"]'.$file.'[/KGVID]');
							
							} else {
....
```
Is there anything I can optimize?

Regards,

**Comment by kylegilman** [comment]
If it's in a file called header.php it's probably not in the loop. Try moving all of your video code into a section of the template after the loop starts. The loop generally starts like this `<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>` but themes may vary. The code `<div class="container">` looks like a good candidate to be the start of the loop.

**Comment by kylegilman** [comment]
Closing old support issues. If you're still experiencing a problem please open a new issue.
