### ISSUE TITLE
Checkboxes auto revert in the queue

### ISSUE THREAD

**Issue by fvdm** [kylegilman/video-embed-thumbnail-generator#356]
While there is a queue it is impossible to toggle any checkbox for files in the encoding queue or their edit pages. Before you can hit the Update button the checkbox state is reverted and then saved with the old state.

At the moment I'm trying to unqueue WEBM encodings but it is impossible. I can only sit back and wait for the line to finish. Very frustrating.

Demo: https://d.pr/v/1e3Oo/1ekGcVno

Edit: This happens in latest Safari and Chrome (osx)

**Comment by kylegilman** [comment]
Yeah, this particular problem is a longstanding bug and happens in any browser. The queue's interactivity has never been particularly robust. Nobody has complained about it before so I haven't taken the time to fix it. It works if you're on a slower server because queue updates happen less frequently when the encoding fps is low, but your 80 fps encodes would make it impossible to click both buttons before the queue is refreshed.

I'm currently doing a complete rewrite of the plugin because a lot of it was written by a really bad programmer (me five years ago) and this was on my list of many things to fix with the queue but that project won't be finished for a long time. I'll see if I can work up a patch to fix this.

**Comment by fvdm** [comment]
Hi, thanks for explaining.

Looking at the admin js I see you reset the checkboxes each time `kgvid_update_encode_queue()` runs. I think it would be better to keep the checked states in a cache var and compare the cached values with the reloaded values. Then only update the checkboxes when there is a change.

Might even reduce stress on the UI when the queue is really long.

**Comment by kylegilman** [comment]
I've been looking at it for the past hour and it's really ugly. That checkbox resetting thing in particular is baffling, but even after fixing that and actually clicking the button, you still can't remove a format from the queue on the queue page. I'll get to the bottom of this in the next few days.

**Comment by fvdm** [comment]
Thanks!

**Comment by kylegilman** [comment]
I committed a patch that seems like it's working. I'd really appreciate it if you can [test it out](https://github.com/kylegilman/video-embed-thumbnail-generator/archive/master.zip).

**Comment by fvdm** [comment]
It works!!
