### ISSUE TITLE
video preload none failed in videojs mode

### ISSUE THREAD

**Issue by panshengjie** [kylegilman/video-embed-thumbnail-generator#361]
in videojs mode, preload=none work as metadata
when I checked video tag, attr preload is marked metadata rather than none

**Comment by kylegilman** [comment]
Preload is not currently a supported shortcode attribute. In order to change the preload option you need to change the plugin settings. I can't think of any reason to leave it out, so I will add preload as an allowed shortcode attribute in the next release.

**Comment by panshengjie** [comment]
I set preload none in plugin settings, dont change anything. still work as metadata

**Comment by kylegilman** [comment]
The page you sent me has preload set to none.

**Comment by panshengjie** [comment]
because it is in wp default mode, this problem occurs in videojs mode

**Comment by kylegilman** [comment]
I understand now. You're seeing this in the browser's inspector console, not the page's source code. If you look at the source code you'll see that it's initially set to none, but in order to switch resolutions, it is necessary to load the metadata, so the resolution switcher script changes preload to metadata.

As we've already determined, the WordPress Default player isn't doing that, but that's a problem. It's actually not working correctly if preload stays on "none". In general I advise against using preload=none. If you're trying to save mobile data usage, you should know that mobile browsers ignore the preload attribute anyway.

**Comment by panshengjie** [comment]
yes, as you mentioned, this shouldn't be a problem on mobile.
but my homepage is consisted of lots videos, if not set to none, that slow down the page load speed.
I wander if it's possible to prevent resolution switcher script changing the preload status before user change the resolution

**Comment by kylegilman** [comment]
Yes, I think I can work out a way to do that.
