### ISSUE TITLE
memory leak in wp background medialibrary video view

### ISSUE THREAD

**Issue by panshengjie** [kylegilman/video-embed-thumbnail-generator#363]
I was viewing some videos in wp media library when the browser breakdown  because of memory leak.
to check the problem, I turn off the plugin and all goes right, which means the plugin introduce the problem.
you can reproduce this by view lots of videos in the media library page, and watch the memory

**Comment by kylegilman** [comment]
Thanks for bringing this to my attention. When the plugin is enabled, every time you load video attachment details in the media library, the video is also loaded so that thumbnails can be created from it. WordPress keeps those attachment detail pages loaded up even when you click away from them. I'll have to figure out a way to hook in to the attachment change event and unload the video when that happens.

**Comment by panshengjie** [comment]
if possible, it's better not to load the video unless click to play

**Comment by kylegilman** [comment]
I agree, that is better, but requires a lot of revision. I'm working on it, but haven't had much time available to devote to this project lately.
