### ISSUE TITLE
kgvid meta data not written at no_replace Uploads

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#371]
Hi,

the no_replace tag at filenames doesn´t encode the original uploaded file, but does also not write the kgvid meta data (duration etc.) to the database. Is it possible to write the meta datas although not encoding?

Regards,

**Comment by kylegilman** [comment]
I guess it depends on which specific information are you looking for in the kgvid metadata array. When I first started working on this plugin, video metadata was only available after running FFMPEG and so it's only written if a video is encoded. Since WordPress version 3.6, a lot of metadata is obtained through ID3 and is available using [`wp_get_attachment_metadata()`](https://developer.wordpress.org/reference/functions/wp_get_attachment_metadata/). For example, duration is stored in the `length` or `length_formatted` key depending on what you want to do with it.

**Comment by benhartwich** [comment]
Thanks, is it possible to get the video id (post_meta => _kgflashmediaplayer-video-id) without encoding the video?

**Comment by kylegilman** [comment]
Sorry for the delay, Christmas got in the way. From what I can tell, the `_kgflashmediaplayer-video-id` metadata entry is only saved on thumbnail images to track the ID of the video it was created from. I don't think there's any reason why it would be saved on a video whether it was encoded using the plugin or not.
