### ISSUE TITLE
VAST support with video.js?

### ISSUE THREAD

**Issue by xporterfield** [kylegilman/video-embed-thumbnail-generator#410]
Is it possible to modify video.js to support VAST with this player?  I've been attempting to hack it in without success.  Something like this: https://www.npmjs.com/package/videojs-vast-vpaid

**Comment by kylegilman** [comment]
It is possible to enqueue additional Video.js plugin scripts, but it's not likely to be an easy fix. My plugin doesn't do anything to prevent it, but there's no system in place to make it any easier for you than doing the whole thing manually.

**Comment by xporterfield** [comment]
I was able to get it (sort of) working with this guide: https://www.jonathan.vc/tech/2017/08/setup-vastvpaid-waterfall-videojs

It's not integrated with your plugin, and I am just doing this to insert the preroll video ad on each single post:

```javascript
<script>
var myPlayer = videojs("video_kgvid_0");

var options = {
    id: 'video_kgvid_0',
    adTagUrl: "https://syndication.exosrv.com/splash.php?idzone=3154068"
};
myPlayer.ima(options);
myPlayer.ima.requestAds();
</script>
```

Could you point me in a direction for integrating this directly inside the plugin?  I've been messing around with kgvid_load_videojs() and kgvid_setup_video() -- but I am not particularly versed in javascript.  Any pointers would be helpful!!  I think I just want to tack those options on every kgvid displayed on the page.

**Comment by kylegilman** [comment]
I've never done this myself because I decided a long time ago that I would only implement advertising in the plugin as a paid premium feature, but I think you could add something like that to the section of kgvid_setup_video() after the line `var player = eval('videojs.players.video_'+id);` so you already have the player object and the player ID (which isn't always kgvid_0). Then something like

```javascript
var options = {
    id: 'video_'+id,
    adTagUrl: "link_to_VAST_XML_file"
};

player.ima(options);
player.ima.requestAds();
```
That assumes the XML file is always the same. And I have no idea how the ima plugin works, so I'm just basing it on your code.
