### ISSUE TITLE
Attach thumbnails to both Post (Featured Image) and Video (Poster)

### ISSUE THREAD

**Issue by edmondoddy** [kylegilman/video-embed-thumbnail-generator#411]
Hi, 

Would be great to have a feature to set Attach thumbnails to both Post (Featured Image) and Video (Poster)

BTW nice plugin. great job 👍

**Comment by kylegilman** [comment]
An attachment can only have one parent in WordPress, so the only way to have both the video and the post be parents of a particular thumbnail image would be to duplicate the media. That seems unnecessary.

Regardless of the thumbnail's parent, you can still use the same thumbnail as both a featured image for a post and the poster image for a video. Is that not working for you?

**Comment by edmondoddy** [comment]
Thanks for fast reply, the thing is that I use the automatic option of the plugin, thumbnails generated when a video gets uploaded via front-end submitter. 

https://imgur.com/a/MtRXhYv

**Comment by edmondoddy** [comment]
Right now I can choose only 1 option, to assign the automatically generated thumbnail to Post featured image, or video poster. 

As the whole process happens in an automatic way, the manual thumbnail set is not preferred.

**Comment by kylegilman** [comment]
An post object (post, attachment, page, they're all "posts" as far as WordPress is concerned) in WordPress can only have one parent. Your problem might be unrelated to the thumbnail parent setting unless I'm misunderstanding what's happening. Does changing that setting give you different results?

Whatever the thumbnail's parent is shouldn't have any effect on whether the video's poster image is assigned automatically and whether the featured image is assigned to the post automatically. That's why there's a separate setting above the "Attach thumbnails" section to "Set generated video thumbnails as featured images." Whether the thumbnail's parent is a post or a video, the plugin should still set the video's parent post's featured image automatically whenever a thumbnail is generated. If that's not happening, then you might have run in to [this bug](https://github.com/kylegilman/video-embed-thumbnail-generator/issues/285) where the frontend uploader doesn't create a post until after the video thumbnail is created, so the plugin doesn't know which post to set the featured image on. Is that what's happening to you?

**Comment by edmondoddy** [comment]
Hi, I got your point, I am very sorry for wasting your time, I didnt understood the plugin's function correctly, now I know what to do, thanks 👍
