### ISSUE TITLE
Remove number after Thumbnailname

### ISSUE THREAD

**Issue by twerpyfie** [kylegilman/video-embed-thumbnail-generator#424]
Hay, is there a way to remove the number after the Thumbnailname. I need it for the free Wonderplugin Gallery plugin. Im not able to set a dynamic Thumbnailsuffix .-. 

It would be greate if there is a easy solution to force the video-embed-thumbnail-generator to not add a number to every thumbnail :>

**Comment by twerpyfie** [comment]
I made it myself. I Made these changes on line 7209 and 7223.
![1234](https://user-images.githubusercontent.com/46491831/51075841-57c35980-1691-11e9-990b-a25b18aa0bb1.png)

**Comment by kylegilman** [comment]
It's a lot more complicated than that. Take a look at all the work I've done on #418 over the past few months. Because of the several different ways the plugin generates thumbnails (saving groups of thumbnails, single thumbnails, using FFMPEG, using built-in browser technology) and the problem of browsers caching image files of the same name, it took me a long time but I don't think I'm going to be able to make all thumbnails have the same filename.

**Comment by twerpyfie** [comment]
Okay that is no problem. You made a greate work and i thought there is maby a simple way :] 👍
