### ISSUE TITLE
No sound on IOS / Iphone

### ISSUE THREAD

**Issue by Playug** [kylegilman/video-embed-thumbnail-generator#541]
Got issue here, my video was running smoothly without problem on any device. Except IOS, when play the video without problem but there is no sound of the video

my site : https://ngetubes.net/chinese/cus005/
*adult content

**Comment by kylegilman** [comment]
That link doesn't work and you appear to have disabled Videopack, but I downloaded a few of your videos and the ones I downloaded have audio encoded with the MPEG-1 Audio Layer 2 (MP2) codec. iOS expects AAC-encoded audio in MP4 containers. As far as I know there's nothing any video player can do to make iOS support MPEG audio in MP4s.

**Comment by Playug** [comment]
Noted, thank you so much for your help.
So the problem is my video audio encoded with MPEG-1 Audio Layer (MP2)
codec.
 Its a quiestion far from the plugin. But  how to change into AAC-encoded
audio?

Regards,

**Comment by kylegilman** [comment]
There are many different tools you could use. You can set the video codec to "copy" or "passthrough" because the video's already in the correct codec so it should be able to convert relatively quickly. One thing to look out for is the setting that optimizes mp4s for streaming by moving the metadata to the beginning of the file. It's called something different in every program.

- I usually just tell people to use [Handbrake](https://handbrake.fr/), but passthrough video is one of the few things Handbrake won't do.
- [FFmpeg ](https://ffmpeg.org/download.html) is the most versatile and the most complicated. I only recommend it if you really know what you're doing. It doesn't have a GUI, but there are a number of GUIs that you can use to interact with FFmpeg. I don't have experience with any of them, so I can't recommend any.
- XMedia Recode for Windows is relatively simple and has good batch-processing.
- [MP4Tools ](https://emmgunn.com/wp/mp4tools-home/) for Mac OS is the most user-friendly.
- [Avidemux](https://avidemux.sourceforge.net/download.html) is a cross-platform option but its batch-processing is kind of confusing.
